In [1]:
import pandas as pd
import numpy as np 
import os
import requests

In [38]:
# Trazendo tabela do wikipedia 
requisicao = requests.get("https://pt.wikipedia.org/wiki/Campeonato_Brasileiro_de_Futebol_de_2017_-_S%C3%A9rie_A")
tabelas = pd.read_html(requisicao.text)

In [106]:
# Definindo tabelas a partir de lista de tabelas
df_artilheiros = tabelas[11]
df_assistencias = tabelas[12]

In [108]:
path= os.getcwd()
path_excel= os.path.join(path,'brasileirao2017.xlsx')

In [110]:
with pd.ExcelWriter(path_excel) as writer:  
    df_artilheiros.to_excel(writer, sheet_name='artilheiros',index=False)
    df_assistencias.to_excel(writer, sheet_name='assistencias',index=False)

In [100]:
df_artilheiros["posicao"] = df_artilheiros.index +1
df_artilheiros["posicao"] = df_artilheiros["posicao"].astype('str')+"°"

df_assistencias["posicao"] = df_assistencias.index +1
df_assistencias["posicao"] = df_assistencias["posicao"].astype('str')+"°"

df_artilheiros = df_artilheiros.rename(columns={'Jogador': 'jogador_gol','Time': 'time_gol'})
df_assistencias = df_assistencias.rename(columns={'Jogador': 'jogador_ass', 'Time':'time_ass'})

In [101]:
df_artilheiros

   Gols[29]       jogador_gol          time_gol posicao
0        18  Henrique Dourado        Fluminense      1°
1        18                Jô       Corinthians      2°
2        16             André             Sport      3°
3        13             Lucca       Ponte Preta      4°
4        12      Edigar Junio             Bahia      5°
5        12              Fred  Atlético Mineiro      6°
6        11       Diego Souza             Sport      7°
7        11      Thiago Neves          Cruzeiro      8°

In [102]:
df_assistencias

   Total[30]      jogador_ass          time_ass posicao
0         12   Gustavo Scarpa        Fluminense      1°
1         11   Bruno Henrique            Santos      2°
2          9   Rodrigo Pimpão          Botafogo      3°
3          8  Agustín Allione             Bahia      4°
4          8     Juan Cazares  Atlético Mineiro      5°
5          8         Reinaldo       Chapecoense      6°
6          8   Thiago Carleto          Coritiba      7°
7          7  Christian Cueva         São Paulo      8°
8          7          Éverton          Flamengo      9°
9          7     Thiago Neves          Cruzeiro     10°

In [103]:
df_posicao = pd.merge(df_assistencias,df_artilheiros,how="left",on="posicao")

In [105]:
df_posicao[["posicao","time_gol","jogador_gol","Gols[29]","time_ass","jogador_ass","Total[30]"]]

,posicao,time_gol,jogador_gol,Gols[29],time_ass,jogador_ass,Total[30]
0,1°,Fluminense,Henrique Dourado,18.0,Fluminense,Gustavo Scarpa,12
1,2°,Corinthians,Jô,18.0,Santos,Bruno Henrique,11
2,3°,Sport,André,16.0,Botafogo,Rodrigo Pimpão,9
3,4°,Ponte Preta,Lucca,13.0,Bahia,Agustín Allione,8
4,5°,Bahia,Edigar Junio,12.0,Atlético Mineiro,Juan Cazares,8
5,6°,Atlético Mineiro,Fred,12.0,Chapecoense,Reinaldo,8
6,7°,Sport,Diego Souza,11.0,Coritiba,Thiago Carleto,8
7,8°,Cruzeiro,Thiago Neves,11.0,São Paulo,Christian Cueva,7
8,9°,NaN,NaN,NaN,Flamengo,Éverton,7
9,10°,NaN,NaN,NaN,Cruzeiro,Thiago Neves,7